on:
  push:
env:
  AWS_REGION: eu-west-2
  AWS_S3_BUCKET_NAME: jd-stock-screener-code
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      # sam build
      - run: sam build --use-container
        name: build

# Run Unit tests- Specify unit tests here
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests/unit/test_handler.py

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket AWS_S3_BUCKET_NAME --capabilities CAPABILITY_IAM --region AWS_REGION
        if: github.ref == 'refs/heads/main'